# AI tools
DOMAIN-SUFFIX,lmstudio.ai

# Media
DOMAIN-SUFFIX,wogg.one
DOMAIN-SUFFIX,wogg.net
DOMAIN-SUFFIX,wogg.lol
DOMAIN-SUFFIX,wogg.xxooo.cf
DOMAIN-SUFFIX,woggpan.888484.xyz
DOMAIN-SUFFIX,woggpan.xxooo.cf
DOMAIN-SUFFIX,woggpan.333232.xyz
DOMAIN-SUFFIX,www.wogg.live
