# $ meta_title Sukka's Ruleset - Polymarket
# $ meta_description This file contains non-IP rules for Polymarket and required trading dependencies.

# >> Polymarket core
DOMAIN-SUFFIX,polymarket.com
DOMAIN-SUFFIX,polymarketexchange.com

# >> Polymarket assets and storage
DOMAIN-KEYWORD,polymarket-upload
DOMAIN-KEYWORD,polymarket-next-images
